export const GET_PLAYERS_START = "GET_PLAYERS_START";
export const GET_PLAYERS_SUCCESS = "GET_PLAYERS_SUCCESS";
export const GET_PLAYERS_FAIL = "GET_PLAYERS_FAIL";

export const GET_PLAYER_START = "GET_PLAYER_START";
export const GET_PLAYER_SUCCESS = "GET_PLAYER_SUCCESS";
export const GET_PLAYER_FAIL = "GET_PLAYER_FAIL";
